libvaladoc/girimporter: Don't guess length of xml header, iterate forward to <repository>
If e.g. the xml header is missing, it resulted in errors like:

    error: expected start element of `repository'
    error: unsupported GIR version (null) (supported: 1.2)