codegen: The actual struct size is required for calloc (POSIX)
Found by -Werror=array-bounds on ppc64el with gcc 10.2 and musl 1.2

basic_types_arrays.c:1268:2: error: 'memcpy' forming offset [8, 23] is
out of the bounds [0, 8] [-Werror=array-bounds]
 1268 |  memcpy (dup, self, sizeof (Foo));
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes https://gitlab.gnome.org/GNOME/vala/issues/1068